### ISSUE TITLE
Is there a way to change the prefix from * to something else?

### ISSUE THREAD

**Issue by RocketFlashXD** [carlodrift/skoice#17]
Hey, this is not really an issue but more like a question/suggestion.

I just wanted to know if there's a way to change the prefix of the bot in the Discord Server.
I would like to change it to something else that fits my server a little better.

If there isn't a way, maybe there should be a way :)

**Comment by carlodrift** [comment]
In the future Skoice 2.1 update, the current commands will be replaced by the Slash Commands integrated in Discord. The prefix will be "/", imposed by Discord and therefore not modifiable

**Comment by carlodrift** [comment]
![image](https://user-images.githubusercontent.com/30211659/147765558-3d9d3964-2ef3-4f76-8b6f-efd9ea67e545.png)
