### ISSUE TITLE
Internal Issue when linking account in game

### ISSUE THREAD

**Issue by BlastyTheDev** [carlodrift/skoice#18]
I am testing this command to see if I can use it with java/bedrock crossplay with the GeyserMC plugin.
When I try to use the /link command to link my account in game, an internal error occurs. Everything else is working fine.
I have provided the in game error message and the server console log when this error occurs.
This server is running Paper version git-Paper-142 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a736c1a)
![image](https://user-images.githubusercontent.com/79897422/149648495-865e419d-6e8b-47a7-b267-7646f86d70ad.png)
![image](https://user-images.githubusercontent.com/79897422/149648566-531d1a0b-b335-4416-922a-7334f09a59f6.png)

**Comment by carlodrift** [comment]
This error is very likely to mean that you have filled out the category ID incorrectly. Please make sure that you have entered the ID of the category in which your main voice channel is contained and not the ID of something else
