### ISSUE TITLE
Proximity chat doesn't properly separate groups of players moving away from each other

### ISSUE THREAD

**Issue by yesido9** [carlodrift/skoice#24]
When 2 players or more move away from a group of players they stay in the same vc well over the block limit set unless they leave 1 by 1 not sure how easy this is to fix but its quite important.

**Comment by TillyMasters1** [comment]
Has this issue been looked into?

**Comment by TillyMasters1** [comment]
i have the same issue, like when there are 4 people and two of them walk away from the other two it seems they just all stay in the same channel sometimes

**Comment by LucasCdry** [comment]
Hey! This has been resolved in the next version of Skoice that is soon to be available. Thank you for reporting the issue.
